name: Publish Artifacts

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  publish-maven:

    runs-on: ubuntu-latest
    env:
      SONATYPE_PGP_PRIVATE_KEY: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY }}
      SONATYPE_PGP_PRIVATE_KEY_PASSWORD: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY_PASSWORD }}
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: temurin
      - run: |
          echo $SONATYPE_PGP_PRIVATE_KEY | base64 --decode > gpg_key
          gpg --import --no-tty --batch --yes gpg_key
          rm gpg_key
          ./mill -i mill.scalalib.PublishModule/publishAll \
            --sonatypeCreds $SONATYPE_USER:$SONATYPE_PASSWORD \
            --gpgArgs --passphrase=$SONATYPE_PGP_PRIVATE_KEY_PASSWORD,--no-tty,--pinentry-mode,loopback,--batch,--yes,-a,-b \
            --publishArtifacts __.publishArtifacts \
            --readTimeout 600000 \
            --awaitTimeout 600000 \
            --release true \
            --signed true

  publish-docs:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: temurin
      - name: publish docs
        shell: 'script -q -e -c "bash {0}"'
        run: echo "Hello World" && ./mill -i publishDocs
        env:
          TERM: xterm-256color

  publish-executable:
    runs-on: ubuntu-latest
    env:
      AMMONITE_BOT_AUTH_TOKEN: ${{ secrets.AMMONITE_BOT_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: temurin
      - run: ./mill -i publishExecutable
